name: Deploy to Staging

on:
  push:
    branches: [ develop ]

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Deploy to Render Staging
        run: |
          # This uses Render's deploy hook feature for staging
          curl -X POST "${{ secrets.RENDER_STAGING_DEPLOY_HOOK_URL }}"
  
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: 'apps/backend/package-lock.json'
      
      - name: Install dependencies
        run: |
          cd apps/backend
          npm ci
      
      - name: Run linting
        run: |
          cd apps/backend
          npm run lint
      
      - name: Run tests
        run: |
          cd apps/backend
          npm test
      
      - name: Build
        run: |
          cd apps/backend
          npm run build 